sudo: false
language: node_js

node_js:
 - 8.10.0

branches:
  except:
    - v0

env:
  global:
    - ISTANBUL_COVERAGE: yes

script:
 - yarn bootstrap --env webpack-4
 - yarn lint
 - yarn test:webpack-2
 - yarn test:webpack-3
 - yarn test:webpack-4

after_success:
 - yarn upload-coverage
